redis:
  host: 127.0.0.1
  port: 6379
redis_audience:
  host: 127.0.0.1
  port: 6379
redis_xmo_connect:
  host: localhost
  port: 6379
redis_cache:
  host: localhost
  port: 6379
redis_trigger:
  host: localhost
  port: 6379
